### ISSUE TITLE
converting to jalali(gregorianToJalali method) calculate wrong date

### ISSUE THREAD

**Issue by javadiahad** [amirmehdizadeh/JalaliCalendar#13]
Hi
There is a problem in converting date to jalali , a compare between the date used in unit test and
http://www.time.ir/ site reveals a bug in JalaliCalendar,for example date "2013, 2, 20"  is equivalent to "1391/12/02" in jalali not "1391/11/30"

or in my sample unit test was not passed test
Calendar cal = Calendar.getInstance();
        cal.set(Calendar.YEAR, 2015);
        cal.set(Calendar.MONTH, 10);
        cal.set(Calendar.DAY_OF_YEAR, 6);
        Assert.assertEquals(JalaliCalendar.gregorianToJalali(new JalaliCalendar.YearMonthDate(cal)).toString(), "1394/07/14");

   public static class YearMonthDate {

```
    public YearMonthDate(int year, int month, int date) {
        this.year = year;
        this.month = month;
        this.date = date;
    }

    public YearMonthDate(Calendar calendar) {            
        this(calendar.get(YEAR),calendar.get(MONTH),calendar.get(DAY_OF_YEAR));
    }
```

**Comment by amirmehdizadeh** [comment]
Hi,
In default calendar of java, month starts with zero and the jalaicalendar follow this rule. for example value of 10 for month is equal to November and in your case "2013,2,20" is equal to 20 March 2013.
if you have any question let me know about it.
Thanks
