### ISSUE TITLE
Maven POM, java.util.Calendar, unit-testing... this library is just perfect!

### ISSUE THREAD

**Issue by ebraminio** [amirmehdizadeh/JalaliCalendar#2]
Do you know a similar implementation for IslamicCalendar? And what do you think about https://github.com/ebraminio/PrayTimes ?
I want use your JaliliCalendar implementation for https://github.com/ebraminio/DroidPersianCalendar is there any obstacle for using it in your opinion?

**Comment by amirmehdizadeh** [comment]
i don't know any similar implementation but certainly there is a lot of implementation for Islamic Calendar, you can use my JalaliCalendar for your project if it useful for you. thank you for use it please send me if you find bug or any problem.
