### ISSUE TITLE
Issue in Leap Year!

### ISSUE THREAD

**Issue by ghost** [amirmehdizadeh/JalaliCalendar#3]
Hi,

I have tested the calendar class and it has an issue in Leap year conversion:

```
    System.out.println(JalaliCalendar.gregorianToJalali(new JalaliCalendar.YearMonthDate(2013, 3, 20)).toString());
    System.out.println(JalaliCalendar.jalaliToGregorian(new JalaliCalendar.YearMonthDate(1391, 12, 30)).toString());
```

output:
        1392/0/31
        2013/3/18

**Comment by amirmehdizadeh** [comment]
dear lightofunity
Thank you for choosing my JalaliCalendar
in GregorianCalenendar and also my JalaliCalendar Months start with zero, it's mean 2013, 3, 20 coincide with 20 ,April 2013 and 1391, 12, 30 coincide with 30 farvardin 1392 So for the first Test answer is correct. but for the second test you are right. i add an exception that don't accept 12 for month.let me know about other issue and any question
Thank you again

**Comment by ghost** [comment]
Thanks dear Amir,

Your clarification was needed indeed, since I was not aware of month 0. I will explore more and get back to you if I need your help.

So far its working fine.

Cheers,
Soheil.
